import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'navigation_drawer.DivisorNav.Principal': 'Main',
      'navigation_drawer.DrawerItem.Home': 'Home',
      'navigation_drawer.DivisorNav.Cadastro Saúde Ocupacional': 'Occupational Health Register',
      'navigation_drawer.DrawerItem.Órgão de classe': 'Class body',
      'navigation_drawer.DrawerItem.Exames': 'Exams',
      'navigation_drawer.DivisorNav.Seguranca de Acesso': 'Access Security',
      'navigation_drawer.DrawerItem.Usuario': 'User',
      'navigation_drawer.DrawerItem.Tipo': 'Type',
      'navigation_drawer.DivisorNav.Relatórios': 'Reports',
      'cabecalho.Image.resorces/brasil.jpg': 'resorces/us.jpg',
      'cabecalho.Row.pt_BR': 'en_US',
      'cabecalho.PopupMenuButton.Idioma': 'Language',
      'cadastro_exame.Cabecalho.Cadastro exame': 'Exam registration',
      'cadastro_exame.Divisor.Parametros': 'Parameters',
      'cadastro_exame.Input.Relatórios': 'Reports',
      'cadastro_exame.Input.Tipo': 'Type',
      'cadastro_exame.Input.Período de':'Period of',
      'cadastro_exame.Input.Período até': 'Period until',
      'cadastro_exame.Input.Status': 'Status',
      'cadastro_exame.ElevatedButton.Executar': 'Run',
      'cadastro_exame.ElevatedButton.Limpar': 'Clean',
      'cadastro_exame.ElevatedButton.Execuções': 'Executions',
      'cadastro_usuario.Cabecalho.Cadastro usuario': 'User registration',
      'cadastro_usuario.Divisor.Dados Login': 'Login Data',
      'cadastro_usuario.Input.Usuario': 'User',
      'cadastro_usuario.Input.ID Integrante': 'Member ID',
      'cadastro_usuario.Input.E-mail': 'Email',
      'cadastro_usuario.Input.Nome': 'Name',
      'cadastro_usuario.Switch.Bloquear Usuario': 'Block User',
      'cadastro_usuario.Divisor.Senha Acesso': 'Password Access',
      'cadastro_usuario.Switch.Autenticar usuario e senha pela rede': 'Authenticate username and password over the network',
      'cadastro_usuario.Switch.Trocar senha no primeiro acesso': 'Change password on first login',
      'cadastro_usuario.Input.Senha': 'Password',
      'cadastro_usuario.Input.Data Expiracao': 'Expiration Date',
      'cadastro_usuario.Input.Confirmar Senha': 'Confirm password',
      'cadastro_usuario.Divisor.Tipo de Acesso': 'Access Type',
      'cadastro_usuario.Input.Grupo de Permissão': 'Permission Group',
      'cadastro_usuario.Input.Grupo de Acesso': 'Access Group',
      'cadastro_usuario.Switch.Administrador': 'Administrator',
      'cadastro_usuario.ElevatedButton.Cancelar': 'Cancel',
      'cadastro_usuario.ElevatedButton.Salvar': 'Save',
      'table_cid_10.Input.Código': 'Code',
      'table_cid_10.Input.Domain Code': 'Domain Code',
      'table_exames.Input.Código': 'Code',
      'table_exames.Input.Descrição': 'Description',
      'login.Input.Login': 'Login',
      'login.Input.Senha': 'Password',
      'login.ElevatedButton.Acessar': 'Access',
      'table_orgao_de_classe.Input.Código': 'Code',
      'table_orgao_de_classe.Input.Domain Code': 'Domain Code',
      'table_type.Input.Código': 'Code',
      'table_type.Input.Domain Code': 'Domain Code',
      'table_type.Text.Type ID': 'Type ID',
      'table_type.Text.Código': 'Code',
      'table_type.Text.Domain code': 'Domain code',
      'table_type.Text.Flex value 01': 'Flex value 01',
      'table_type.Text.Flex value 02': 'Flex value 01',
      'table_type.Text.Is new': 'Is new',
      'table_type.Text.Updated': 'Updated',
      'table_type.Text.Created by': 'Created by',
      'table_type.Text.Creation date': 'Creation date',
      'table_type.Text.Last update date': 'Last update date',
      'table_type.Text.Last updated by': 'Last updated by',
      'table_type.Text.Table name': 'Table name',
      'table_usuario.Input.Login': 'Login',
      'table_usuario.Input.Nome': 'Name',
      'table_usuario.ElevatedButton.Adicionar usuario': 'Add user',
      'table_usuario.Text.User Id': 'User ID',
      'table_usuario.Text.Language Code': 'Language Code',
      'table_usuario.Text.Created By': 'Created By',
      'table_usuario.Text.Creation Date': 'Creation Date',
      'table_usuario.Text.Last Updated By': 'Last Updated By',
      'table_usuario.Text.Last Update Date': 'Last Update Date',
      'table_usuario.Text.User  Name': 'User  Name',
      'table_usuario.Text.EmplId': 'EmplId',
      'table_usuario.Text.blocked': 'blocked',
      'table_usuario.Text.authenticate': 'authenticate',
      'table_usuario.Text.changePasswordFirstAccess': 'changePasswordFirstAccess',
      'table_usuario.Text.expirationDate': 'expirationDate',
      'table_usuario.Text.lastAccessDate': 'lastAccessDate',
      'table_usuario.Text.encryptedUserPassword': 'encryptedUserPassword',
      'table_usuario.Text.sysAdmin': 'sysAdmin',
      'table_usuario.Text.userAccessFunctionList': 'userAccessFunctionList',
      'table_usuario.Text.userPermissionGroup': 'userPermissionGroup',
      'exames.Cabecalho.Exames': 'Exams',
      'orgao_de_classe.Cabecalho.Órgão de Classe': 'Class body',
      'type.Cabecalho.Type' : 'Type',
      'usuario.Cabecalho.Usuario': 'User',
      'navigation_drawer.ItemUsuario.Tooltip.editar': 'edit',
      'navigation_drawer.ItemUsuario.Tooltip.configurações': 'settings',
      'navigation_drawer.ItemUsuario.Tooltip.sair': 'go out',
      'navigation_drawer.SearchField.TextField.Buscar': 'Search',
      'Configuracao.Cabecalho.Configuração': 'Settings',
    },
    'es_ES': {
      'navigation_drawer.DivisorNav.Principal': 'Principal',
      'navigation_drawer.DrawerItem.Home': 'Home',
      'navigation_drawer.DivisorNav.Cadastro Saúde Ocupacional': 'Registro de Salud Ocupacional',
      'navigation_drawer.DrawerItem.Órgão de classe': 'Cuerpo de clase',
      'navigation_drawer.DrawerItem.Exames': 'Examenes',
      'navigation_drawer.DivisorNav.Seguranca de Acesso':'Seguridad de Acceso',
      'navigation_drawer.DrawerItem.Usuario': 'Usuario',
      'navigation_drawer.DrawerItem.Tipo': 'Escribe',
      'navigation_drawer.DivisorNav.Relatórios' : 'Informes',
      'cabecalho.Image.resorces/brasil.jpg': 'resorces/espanha.jpg',
      'cabecalho.Row.pt_BR': 'es_ES',
      'cabecalho.PopupMenuButton.Idioma': 'Idioma',
      'cadastro_exame.Cabecalho.Cadastro exame': 'Registro de examen',
      'cadastro_exame.Divisor.Parametros': 'Parámetros',
      'cadastro_exame.Input.Relatórios': 'Informes',
      'cadastro_exame.Input.Tipo': 'Escribe',
      'cadastro_exame.Input.Período de':'Periodo de',
      'cadastro_exame.Input.Período até': 'Período hasta',
      'cadastro_exame.Input.Status': 'Estado',
      'cadastro_exame.ElevatedButton.Executar': 'Correr',
      'cadastro_exame.ElevatedButton.Limpar': 'Limpio',
      'cadastro_exame.ElevatedButton.Execuções': 'Ejecuciones',
      'cadastro_usuario.Cabecalho.Cadastro usuario': 'Registro de usuario',
      'cadastro_usuario.Divisor.Dados Login': 'Datos de inicio de sesión',
      'cadastro_usuario.Input.Usuario': 'Usuario',
      'cadastro_usuario.Input.ID Integrante': 'ID Miembro',
      'cadastro_usuario.Input.E-mail':'Correo electrónico',
      'cadastro_usuario.Input.Nome': 'Nombre',
      'cadastro_usuario.Switch.Bloquear Usuario': 'Bloquear Usuario',
      'cadastro_usuario.Divisor.Senha Acesso': 'Acceso con contraseña',
      'cadastro_usuario.Switch.Autenticar usuario e senha pela rede': 'Autenticar nombre de usuario y contraseña a través de la red',
      'cadastro_usuario.Switch.Trocar senha no primeiro acesso': 'Cambiar contraseña en el primer \ninicio de sesión',
      'cadastro_usuario.Input.Senha': 'Clave',
      'cadastro_usuario.Input.Data Expiracao': 'Fecha de caducidad',
      'cadastro_usuario.Input.Confirmar Senha': 'Confirmar seña',
      'cadastro_usuario.Divisor.Tipo de Acesso': 'Tipo de Acesso',
      'cadastro_usuario.Input.Grupo de Permissão': 'Grupo de permisos',
      'cadastro_usuario.Input.Grupo de Acesso': 'Grupo de acceso',
      'cadastro_usuario.Switch.Administrador': 'Administrador',
      'cadastro_usuario.ElevatedButton.Cancelar': 'Cancelar',
      'cadastro_usuario.ElevatedButton.Salvar': 'Ahorrar',
      'table_cid_10.Input.Código': 'Código',
      'table_cid_10.Input.Domain Code': 'Domain Code',
      'table_exames.Input.Código': 'Código',
      'table_exames.Input.Descrição': 'Descripción',
      'login.Input.Login': 'Acceso',
      'login.Input.Senha': 'Clave',
      'login.ElevatedButton.Acessar': 'Acceso',
      'table_orgao_de_classe.Input.Código': 'Código',
      'table_orgao_de_classe.Input.Domain Code': 'Domain Code',
      'table_type.Input.Código': 'Código',
      'table_type.Input.Domain Code': 'Domain Code',
      'table_type.Text.Type ID': 'Tipo ID',
      'table_type.Text.Código': 'Código',
      'table_type.Text.Domain code': 'Domain code',
      'table_type.Text.Flex value 01': 'Valor flexible 01',
      'table_type.Text.Flex value 02': 'Valor flexible 02',
      'table_type.Text.Is new': 'És nuevo',
      'table_type.Text.Updated': 'Actualizado',
      'table_type.Text.Created by': 'Criado por',
      'table_type.Text.Creation date': 'Fecha de creación',
      'table_type.Text.Last update date': 'Última Fecha de Actualización',
      'table_type.Text.Last updated by': 'Última actualización por',
      'table_type.Text.Table name': 'Nombre de la tabla',
      'table_usuario.Input.Login': 'Acceso',
      'table_usuario.Input.Nome': 'Nombre',
      'table_usuario.ElevatedButton.Adicionar usuario': 'Agregar usuario',
      'table_usuario.Text.User Id': 'Usuario ID',
      'table_usuario.Text.Language Code': 'Código de lenguaje',
      'table_usuario.Text.Created By': 'Creado por',
      'table_usuario.Text.Creation Date': 'Fecha de creación',
      'table_usuario.Text.Last Updated By': 'Última actualización por',
      'table_usuario.Text.Last Update Date': 'Última Fecha de Actualización',
      'table_usuario.Text.User  Name': 'Nombre de usuario',
      'table_usuario.Text.EmplId': 'EmplId',
      'table_usuario.Text.blocked': 'obstruido',
      'table_usuario.Text.authenticate': 'autenticar',
      'table_usuario.Text.changePasswordFirstAccess': 'cambiarContraseñaPrimerAcceso',
      'table_usuario.Text.expirationDate': 'fechaDeCaducidad',
      'table_usuario.Text.lastAccessDate': 'últimaFechaDeAcceso',
      'table_usuario.Text.encryptedUserPassword': 'contraseñaDeUsuarioEncriptada',
      'table_usuario.Text.sysAdmin': 'sysAdmin',
      'table_usuario.Text.userAccessFunctionList': 'listaFuncionesDeAccesoDelUsuario',
      'table_usuario.Text.userPermissionGroup': 'grupoDePermisosDeUsuario',
      'exames.Cabecalho.Exames': 'Examenes',
      'orgao_de_classe.Cabecalho.Órgão de Classe': 'Cuerpo de clase',
      'type.Cabecalho.Type' : 'Escribe',
      'usuario.Cabecalho.Usuario': 'Usuario',
      'navigation_drawer.ItemUsuario.Tooltip.editar': 'editar',
      'navigation_drawer.ItemUsuario.Tooltip.configurações': 'ajustes',
      'navigation_drawer.ItemUsuario.Tooltip.sair': 'salir',
      'navigation_drawer.SearchField.TextField.Buscar': 'Búsqueda',
      'Configuracao.Cabecalho.Configuração': 'Ajustes',
    },
    'pt_BR': {
      'navigation_drawer.DivisorNav.Principal': 'Principal',
      'navigation_drawer.DrawerItem.Home': 'Home',
      'navigation_drawer.DivisorNav.Cadastro Saúde Ocupacional': 'Cadastro Saúde Ocupacional',
      'navigation_drawer.DrawerItem.Órgão de classe':'Órgão de classe',
      'navigation_drawer.DrawerItem.Exames': 'Exames',
      'navigation_drawer.DivisorNav.Seguranca de Acesso' :'Seguranca de Acesso',
      'navigation_drawer.DrawerItem.Usuario': 'Usuario',
      'navigation_drawer.DrawerItem.Tipo': 'Tipo',
      'navigation_drawer.DivisorNav.Relatórios': 'Relatórios',
      'cabecalho.Image.resorces/brasil.jpg': 'resorces/brasil.jpg',
      'cabecalho.Row.pt_BR': 'pt_BR',
      'cabecalho.PopupMenuButton.Idioma': 'Idioma',
      'cadastro_exame.Cabecalho.Cadastro exame': 'Cadastro exame',
      'cadastro_exame.Divisor.Parametros': 'Parametros',
      'cadastro_exame.Input.Relatórios': 'Relatórios',
      'cadastro_exame.Input.Tipo': 'Tipo',
      'cadastro_exame.Input.Período de':'Período de',
      'cadastro_exame.Input.Período até': 'Período até',
      'cadastro_exame.Input.Status': 'Status',
      'cadastro_exame.ElevatedButton.Executar': 'Executar',
      'cadastro_exame.ElevatedButton.Limpar': 'Limpar',
      'cadastro_exame.ElevatedButton.Execuções': 'Execuções',
      'cadastro_usuario.Cabecalho.Cadastro usuario': 'Cadastro usuario',
      'cadastro_usuario.Divisor.Dados Login': 'Dados Login',
      'cadastro_usuario.Input.Usuario': 'Usuario',
      'cadastro_usuario.Input.ID Integrante': 'ID Integrante',
      'cadastro_usuario.Input.E-mail': 'E-mail',
      'cadastro_usuario.Input.Nome': 'Nome',
      'cadastro_usuario.Switch.Bloquear Usuario': 'Bloquear Usuario',
      'cadastro_usuario.Divisor.Senha Acesso': 'Senha Acesso',
      'cadastro_usuario.Switch.Autenticar usuario e senha pela rede': 'Autenticar usuario e senha pela rede',
      'cadastro_usuario.Switch.Trocar senha no primeiro acesso': 'Trocar senha no primeiro acesso',
      'cadastro_usuario.Input.Senha': 'Senha',
      'cadastro_usuario.Input.Data Expiracao': 'Data Expiracao',
      'cadastro_usuario.Input.Confirmar Senha': 'Confirmar Senha',
      'cadastro_usuario.Divisor.Tipo de Acesso': 'Tipo de Acesso',
      'cadastro_usuario.Input.Grupo de Permissão': 'Grupo de Permissão',
      'cadastro_usuario.Input.Grupo de Acesso': 'Grupo de Acesso',
      'cadastro_usuario.Switch.Administrador': 'Administrador',
      'cadastro_usuario.ElevatedButton.Cancelar': 'Cancelar',
      'cadastro_usuario.ElevatedButton.Salvar': 'Salvar',
      'table_cid_10.Input.Código': 'Código',
      'table_cid_10.Input.Domain Code': 'Domain Code',
      'table_exames.Input.Código': 'Código',
      'table_exames.Input.Descrição': 'Descrição',
      'login.Input.Login': 'Login',
      'login.Input.Senha': 'Senha',
      'login.ElevatedButton.Acessar': 'Acessar',
      'table_orgao_de_classe.Input.Código': 'Código',
      'table_orgao_de_classe.Input.Domain Code': 'Domain Code',
      'table_type.Input.Código': 'Código',
      'table_type.Input.Domain Code': 'Domain Code',
      'table_type.Text.Type ID': 'Tipo ID',
      'table_type.Text.Código': 'Código',
      'table_type.Text.Domain code': 'Domain code',
      'table_type.Text.Flex value 01': 'Valor flexível 01',
      'table_type.Text.Flex value 02': 'Valor flexível 02',
      'table_type.Text.Is new': 'É novo',
      'table_type.Text.Updated': 'Atualizado',
      'table_type.Text.Created by': 'Criado por',
      'table_type.Text.Creation date': 'Data de criação',
      'table_type.Text.Last update date': 'Data da última atualização',
      'table_type.Text.Last updated by': 'Última atualização por',
      'table_type.Text.Table name': 'Nome da tabela',
      'table_usuario.Input.Login': 'Login',
      'table_usuario.Input.Nome': 'Nome',
      'table_usuario.ElevatedButton.Adicionar usuario': 'Adicionar usuario',
      'table_usuario.Text.User Id': 'ID do usuário',
      'table_usuario.Text.Language Code': 'Código do idioma',
      'table_usuario.Text.Created By': 'Criado por',
      'table_usuario.Text.Creation Date': 'Data de criação',
      'table_usuario.Text.Last Updated By': 'Atualizado por',
      'table_usuario.Text.Last Update Date': 'Data da ultima atualização',
      'table_usuario.Text.User Name': 'Nome do usuario',
      'table_usuario.Text.EmplId': 'EmplId',
      'table_usuario.Text.blocked': 'bloqueado',
      'table_usuario.Text.authenticate': 'autenticar',
      'table_usuario.Text.changePasswordFirstAccess': 'alterarSenhaDePrimeiroAcesso',
      'table_usuario.Text.expirationDate': 'dataDeValidade',
      'table_usuario.Text.lastAccessDate': 'últimaDataDeAcesso',
      'table_usuario.Text.encryptedUserPassword': 'senhaDeUsuárioCriptografada',
      'table_usuario.Text.sysAdmin': 'sysAdmin',
      'table_usuario.Text.userAccessFunctionList': 'listaDeFunçõesDeAcessoDoUsuário',
      'table_usuario.Text.userPermissionGroup': 'grupoDePermissõesDoUsuário',
      'exames.Cabecalho.Exames': 'Exames',
      'orgao_de_classe.Cabecalho.Órgão de Classe': 'Órgão de Classe',
      'type.Cabecalho.Type' : 'Tipo',
      'usuario.Cabecalho.Usuario': 'Usuario',
      'navigation_drawer.ItemUsuario.Tooltip.editar': 'editar',
      'navigation_drawer.ItemUsuario.Tooltip.configurações': 'configurações',
      'navigation_drawer.ItemUsuario.Tooltip.sair': 'sair',
      'navigation_drawer.SearchField.TextField.Buscar': 'Buscar',
      'Configuracao.Cabecalho.Configuração': 'Configuração',
    }
  };

}